# Generated by Django 5.2.3 on 2025-09-19 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_manage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='blog',
            new_name='user',
        ),
    ]
