# Generated by Django 5.2.3 on 2025-09-22 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_manage', '0002_rename_blog_blogpost_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='visibility',
            field=models.CharField(default='public', max_length=40),
        ),
    ]
